# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d4020cc25fb0d7de9de3ab325fc7bfe9a44a73e890f6abcd7af466ad05c35e5577e5b997452fb6eed4c62ef4f7f49a984d17c17cc8be65cd6c4eb4de9236b4c

test:
  secret_key_base: 82a32a24636255ea4bef778359628542cf43b11e8cb79bfd71fda7f152293ad5077f137a1f4e141319b56898e0ffcb04b156271dc4adcb96ea823639350462e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
